// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/29/2026, 12:55:16 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/bfree/Desktop/booluw/AorB/aorb/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/plugins/**/*.{js,ts,mjs}","/Users/bfree/Desktop/booluw/AorB/aorb/composables/**/*.{js,ts,mjs}","/Users/bfree/Desktop/booluw/AorB/aorb/utils/**/*.{js,ts,mjs}","/Users/bfree/Desktop/booluw/AorB/aorb/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/bfree/Desktop/booluw/AorB/aorb/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;